# Generated by Django 5.2.8 on 2025-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Not Yet Decided', 'Not Yet Decided'), ('Process Improvement', 'Process Improvement'), ('IT Governance', 'IT Governance'), ('AI Governance', 'AI Governance'), ('ERP Governance', 'ERP Governance')], default='Not Yet Decided', max_length=50),
        ),
    ]
