# Generated by Django 5.2.8 on 2025-11-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Top', 'Top')], default='Normal', max_length=20),
        ),
    ]
