# Generated by Django 5.2.8 on 2025-11-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_request_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cost_benefit',
            field=models.IntegerField(blank=True, help_text='Cost benefit score (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='ease_of_implementation',
            field=models.IntegerField(blank=True, help_text='Ease of implementation score (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='final_priority',
            field=models.IntegerField(blank=True, help_text='Project ranking (lower number = higher priority)', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='final_score',
            field=models.FloatField(blank=True, help_text='Final score', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='request_id',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='scoring_notes',
            field=models.TextField(blank=True, help_text='Notes related to project scoring or evaluation', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='security_compliance',
            field=models.IntegerField(blank=True, help_text='Security and compliance score (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='strategic_alignment',
            field=models.IntegerField(blank=True, help_text='Strategic alignment score (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='student_centered',
            field=models.IntegerField(blank=True, help_text='Student-centered score (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_impact',
            field=models.IntegerField(blank=True, help_text='User impact and adoption score (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='vendor_reputation_support',
            field=models.IntegerField(blank=True, help_text='Vendor reputation and support score (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='stage',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Under Review - Triage', 'Under Review - Triage'), ('Under Review - Governance', 'Under Review - Governance'), ('Under Review - Final Governance', 'Under Review - Final Governance'), ('Approved', 'Recommended'), ('Rejected', 'Not Recommended')], default='Pending Review', max_length=50),
        ),
    ]
