# Generated by Django 5.2.8 on 2025-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_make_request_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
