# Generated by Django 5.2.8 on 2025-11-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_requestattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='triage_notes',
            field=models.TextField(blank=True, help_text='Notes from the triage group', null=True),
        ),
    ]
