# Generated by Django 5.2.8 on 2025-11-19 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_triagenoteshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field that was changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='app.request')),
            ],
            options={
                'verbose_name_plural': 'Request Change History',
                'ordering': ['-changed_at'],
            },
        ),
    ]
